'use server'

import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
import { Database } from '@/types/database.types'
import { SupabaseClient } from '@supabase/supabase-js'
import { createMasterInvoice } from './master-invoices'

export async function getInvoices() {
    const supabase = (await createClient()) as SupabaseClient<Database>
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return []

    const { data: profile } = await supabase
        .from('profiles')
        .select('company_id')
        .eq('id', user.id)
        .single() as any

    if (!profile?.company_id) return []

    // Fetch Standard Invoices (where master_invoice_id IS NULL)
    // AND Master Invoices? Or just invoices?
    // Requirement: "Master Invoice View should show Total contract value... Expandable phase breakdown"
    // So main list likely shows Standard Invoices + Master Invoices.
    // Child phases shouldn't clutter the main list maybe? Or maybe they should?
    // Let's filter out CHILD phases from main list for clarity?
    // "Phase Invoices (Children)... Payments are accepted ONLY on phase invoices"
    // If I hide them, user can't find them to pay.
    // So maybe show ALL. But distinguishing them is key.

    const { data: invoices } = await (supabase
        .from('invoices') as any)
        .select(`
            *, 
            customer_snapshot,
            master_invoice:master_invoices(master_invoice_number)
        `)
        .eq('company_id', profile.company_id)
        .eq('is_deleted', false)
        .order('created_at', { ascending: false })

    return invoices || []
}

export async function createInvoice(prevState: any, formData: FormData) {
    const supabase = (await createClient()) as SupabaseClient<Database>
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { message: 'Not authenticated' }

    // Parse raw form data
    const rawData = formData.get('data') as string
    if (!rawData) return { message: 'No data provided' }

    const input = JSON.parse(rawData)

    // Check for Master Invoice Mode
    if (input.isMaster) {
        return await createMasterInvoice(prevState, formData)
    }

    // Validation would go here (Zod)

    const { data: profile } = await supabase
        .from('profiles')
        .select('company_id')
        .eq('id', user.id)
        .single() as any

    if (!profile?.company_id) return { message: 'No company found' }

    // 1. Get Company Snapshot
    const { data: company } = await (supabase
        .from('companies') as any)
        .select('*')
        .eq('id', profile.company_id)
        .single()

    // 2. Get Party Snapshot
    const { data: party } = await (supabase
        .from('parties') as any)
        .select('*')
        .eq('id', input.customerId)
        .single()

    if (!party) return { message: 'Customer not found' }

    // 3. Create Invoice Record
    const { data: invoice, error: invoiceError } = await (supabase.from('invoices') as any)
        .insert({
            company_id: profile.company_id,
            customer_id: input.customerId,
            // invoice_number is auto-generated by DB Trigger (Atomic)
            date: input.date,
            due_date: input.dueDate,
            status: 'draft',
            tax_mode: input.taxMode || (input.isTaxInclusive ? 'inclusive' : 'exclusive'),
            subtotal: input.totals.subtotal,
            tax_total: input.totals.totalCGST + input.totals.totalSGST + input.totals.totalIGST,
            grand_total: input.totals.grandTotal,
            tds_rate: input.tdsRate,
            tds_amount: input.tdsAmount || input.totals.tdsAmount, // Check both sources
            net_receivable: input.netReceivable || input.totals.netReceivable,
            customer_snapshot: party,
            company_snapshot: company,
            created_by: user.id
        })
        .select()
        .single()

    if (invoiceError) {
        console.error(invoiceError)
        return { message: 'Error creating invoice: ' + invoiceError.message }
    }

    // 4. Create Invoice Items
    const itemsPayload = input.lineItems.map((item: any) => ({
        invoice_id: invoice.id,
        item_id: item.item_id,
        description: item.description,
        sac_code: item.sac_code,
        quantity: item.quantity,
        unit_price: item.unit_price,
        tax_rate: item.tax_rate,
        taxable_amount: item.taxable,
        cgst_amount: item.cgst,
        sgst_amount: item.sgst,
        igst_amount: item.igst,
        total_amount: item.total
    }))

    const { error: itemsError } = await (supabase.from('invoice_items') as any)
        .insert(itemsPayload)

    if (itemsError) {
        // Rollback typically? For MVP we just report error.
        console.error(itemsError)
        return { message: 'Error creating line items' }
    }


    // --- BACKUP SYSTEM REMOVED FROM DRAFT CREATION ---
    // Backups should only occur upon FINALIZATION to ensure audit trail integrity.

    revalidatePath('/dashboard/invoices')
    return { message: 'success', invoiceId: invoice.id }
}

export async function getNextInvoiceNumber() {
    // Generate auto-increment invoice number
    // Format: INV/YYYY/001
    // MVP: Simple count + 1 or max + 1
    const supabase = (await createClient()) as SupabaseClient<Database>
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return 'INV-001'

    // Get company ID
    const { data: profile } = await supabase
        .from('profiles')
        .select('company_id')
        .eq('id', user.id)
        .single() as any

    if (!profile?.company_id) return 'INV-001'

    const { data: invoices } = await (supabase.from('invoices') as any)
        .select('invoice_number')
        .eq('company_id', profile.company_id)
        .order('created_at', { ascending: false })
        .limit(1)

    if (invoices && invoices.length > 0) {
        const lastNum = invoices[0].invoice_number
        // Try to parse number
        const parts = lastNum.split('-')
        const num = parseInt(parts[parts.length - 1])
        if (!isNaN(num)) {
            return `INV-${String(num + 1).padStart(3, '0')}`
        }
    }

    return 'INV-001'
}

export async function getInvoice(id: string) {
    const supabase = (await createClient()) as SupabaseClient<Database>
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return null

    // Fetch invoice with items
    // Fetch invoice with items and OPTIONAL Master Invoice details
    const { data: invoice } = await (supabase
        .from('invoices') as any)
        .select(`
            *, 
            invoice_items(*),
            master_invoice:master_invoices (
                master_invoice_number
            )
        `)
        .eq('id', id)
        .single()


    return invoice
}

export async function finalizeInvoice(id: string) {
    const supabase = (await createClient()) as SupabaseClient<Database>
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { message: 'Not authenticated' }

    // Check ownership & status
    const { data: invoice } = await (supabase.from('invoices') as any)
        .select('*, invoice_items(*)')
        .eq('id', id)
        .single()
    if (!invoice) return { message: 'Invoice not found' }

    // Verify company
    const { data: profile } = await (supabase.from('profiles') as any).select('company_id').eq('id', user.id).single()
    if (invoice.company_id !== profile?.company_id) return { message: 'Unauthorized' }

    if (invoice.status !== 'draft') return { message: 'Invoice is already finalized or cancelled' }

    // Update status to finalized
    const { error } = await (supabase.from('invoices') as any)
        .update({ status: 'finalized' })
        .eq('id', id)

    if (error) return { message: 'Error finalizing invoice' }

    // --- CREATE TDS LEDGER ENTRY (COMPLIANCE) ---
    if (invoice.tds_amount && invoice.tds_amount > 0) {
        const invoiceDate = new Date(invoice.date);
        const month = invoiceDate.getMonth(); // 0 = Jan
        const year = invoiceDate.getFullYear();
        let fy = '';
        if (month < 3) {
            fy = `${year - 1}-${(year).toString().slice(-2)}`;
        } else {
            fy = `${year}-${(year + 1).toString().slice(-2)}`;
        }

        const tdsEntry = {
            company_id: profile.company_id,
            invoice_id: id,
            customer_id: invoice.customer_id, // Ensure this exists on invoice or use customer_snapshot.id? 
            // invoice.customer_id is nullable in schema but required for finalized?
            // If null, we can try to use snapshot id.
            // But let's assume valid Invoice has customer_id.
            financial_year: fy,
            taxable_value: invoice.subtotal,
            tds_rate: invoice.tds_rate,
            tds_amount: invoice.tds_amount,
            section_code: '194J', // Default
            deducted_on: invoice.date,
            status: 'pending'
        }

        // We use upsert to be safe on re-runs (idempotent) if we had a unique constraint, but we don't.
        // So checking existence first or just insert? User asked for "Enforce ONE TDS record".
        // Let's check if exists.
        const { count } = await (supabase.from('tds_ledger') as any)
            .select('*', { count: 'exact', head: true })
            .eq('invoice_id', id)

        if (count === 0) {
            await (supabase.from('tds_ledger') as any).insert(tdsEntry)
        }
    }

    // --- TRIGGER BACKUP EMAIL (AUDIT COMPLIANT) ---
    try {
        // Fetch remaining details needed for proper PDF generation
        const { data: company } = await (supabase.from('companies') as any).select('*').eq('id', profile.company_id).single()

        const customer = invoice.customer_snapshot || {}

        if (company && invoice.invoice_items) {
            const { BackupService } = await import('@/lib/backup-service')
            await BackupService.backupInvoice(invoice, invoice.invoice_items, company, customer)
        }

        // --- AUDIT LOG ---
        const { logAuditEvent } = await import('./audit')
        await logAuditEvent(
            'invoices',
            id,
            'finalize',
            { status: 'draft' },
            { status: 'finalized', tds_entry: Boolean(invoice.tds_amount) },
            `Invoice ${invoice.invoice_number} finalized by ${user.email}`
        )

    } catch (e) {
        console.error('[Finalize] Backup/Audit Failed:', e)
        // We do NOT rollback transaction based on email failure, per compliance reqs.
    }

    revalidatePath(`/dashboard/invoices/${id}`)
    revalidatePath('/dashboard/invoices')
    return { message: 'success' }
}

export async function deleteInvoice(id: string) {
    const supabase = (await createClient()) as SupabaseClient<Database>
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { message: 'Not authenticated' }

    const { data: invoice } = await (supabase.from('invoices') as any).select('status, company_id').eq('id', id).single()
    if (!invoice) return { message: 'Invoice not found' }

    const { data: profile } = await (supabase.from('profiles') as any).select('company_id').eq('id', user.id).single()
    if (invoice.company_id !== profile?.company_id) return { message: 'Unauthorized' }

    if (invoice.status !== 'draft') return { message: 'Only Draft invoices can be deleted. Please cancel finalized invoices.' }

    // Attempt Soft Delete first (requires is_deleted column)
    const { error: softDeleteError } = await (supabase.from('invoices') as any)
        .update({ is_deleted: true })
        .eq('id', id)

    if (softDeleteError) {
        console.warn('Soft delete failed (likely missing column), attempting hard delete...', softDeleteError)

        // Fallback: Hard Delete (Safe for Drafts)
        const { error: hardDeleteError } = await (supabase.from('invoices') as any)
            .delete()
            .eq('id', id)

        if (hardDeleteError) {
            console.error('Hard Delete Error:', hardDeleteError)
            return { message: `Error deleting invoice: ${hardDeleteError.message}` }
        }
    }

    revalidatePath('/dashboard/invoices')
    return { message: 'success' }
}

export async function cancelInvoice(id: string, reason: string) {
    const supabase = (await createClient()) as SupabaseClient<Database>
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { message: 'Not authenticated' }

    if (!reason || reason.trim().length < 5) return { message: 'Reason is required (min 5 chars)' }

    // Check ownership
    const { data: invoice } = await (supabase.from('invoices') as any).select('status, company_id').eq('id', id).single()
    if (!invoice) return { message: 'Invoice not found' }

    const { data: profile } = await (supabase.from('profiles') as any).select('company_id').eq('id', user.id).single()
    if (invoice.company_id !== profile?.company_id) return { message: 'Unauthorized' }

    if (invoice.status === 'cancelled') return { message: 'Invoice is already cancelled' }

    // Attempt Cancel with Reason
    const { error } = await (supabase.from('invoices') as any)
        .update({
            status: 'cancelled',
            cancel_reason: reason
        })
        .eq('id', id)

    if (error) {
        console.warn('Cancel with reason failed (likely missing column), attempting status update only...', error)

        // Fallback: Update status only
        const { error: fallbackError } = await (supabase.from('invoices') as any)
            .update({ status: 'cancelled' })
            .eq('id', id)

        if (fallbackError) {
            console.error('Cancel Fallback Error:', fallbackError)
            return { message: `Error cancelling invoice: ${fallbackError.message}` }
        }
    }

    revalidatePath(`/dashboard/invoices/${id}`)
    revalidatePath('/dashboard/invoices')
    return { message: 'success' }
}

export async function updateInvoice(id: string, prevState: any, formData: FormData) {
    const supabase = (await createClient()) as SupabaseClient<Database>
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { message: 'Not authenticated' }

    const rawData = formData.get('data') as string
    if (!rawData) return { message: 'No data provided' }

    const input = JSON.parse(rawData)

    // Check ownership
    const { data: invoice } = await (supabase.from('invoices') as any).select('status, company_id').eq('id', id).single()
    if (!invoice) return { message: 'Invoice not found' }

    const { data: profile } = await (supabase.from('profiles') as any).select('company_id').eq('id', user.id).single()
    if (invoice.company_id !== profile?.company_id) return { message: 'Unauthorized' }

    if (invoice.status === 'finalized' || invoice.status === 'paid') {
        return { message: 'Cannot edit finalized or paid invoices' }
    }

    // Update Invoice Record
    const { error: invoiceError } = await (supabase.from('invoices') as any)
        .update({
            customer_id: input.customerId,
            date: input.date,
            due_date: input.dueDate,
            tax_mode: input.taxMode || (input.isTaxInclusive ? 'inclusive' : 'exclusive'),
            subtotal: input.totals.subtotal,
            tax_total: input.totals.totalCGST + input.totals.totalSGST + input.totals.totalIGST,
            grand_total: input.totals.grandTotal,
            tds_rate: input.tdsRate,
            tds_amount: input.tdsAmount || input.totals.tdsAmount,
            net_receivable: input.netReceivable || input.totals.netReceivable
        })
        .eq('id', id)

    if (invoiceError) {
        console.error(invoiceError)
        return { message: 'Error updating invoice: ' + invoiceError.message }
    }

    // Update Items: Delete existing and re-insert (easiest for MVP)
    // Or simpler: just delete all items for this invoice and recreate
    const { error: deleteError } = await (supabase.from('invoice_items') as any).delete().eq('invoice_id', id)
    if (deleteError) return { message: 'Error updating items (delete failed)' }

    const itemsPayload = input.lineItems.map((item: any) => ({
        invoice_id: id,
        item_id: item.item_id,
        description: item.description,
        sac_code: item.sac_code,
        quantity: item.quantity,
        unit_price: item.unit_price,
        tax_rate: item.tax_rate,
        taxable_amount: item.taxable,
        cgst_amount: item.cgst,
        sgst_amount: item.sgst,
        igst_amount: item.igst,
        total_amount: item.total
    }))

    const { error: itemsError } = await (supabase.from('invoice_items') as any)
        .insert(itemsPayload)

    if (itemsError) {
        console.error(itemsError)
        return { message: 'Error recreating line items' }
    }

    revalidatePath(`/dashboard/invoices/${id}`)
    revalidatePath('/dashboard/invoices')
    return { message: 'success', invoiceId: id }
}
