'use server'

import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
import { Database } from '@/types/database.types'
import { SupabaseClient } from '@supabase/supabase-js'

export async function getPayments() {
    const supabase = (await createClient()) as SupabaseClient<Database>
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return []

    const { data: profile } = await supabase
        .from('profiles')
        .select('company_id')
        .eq('id', user.id)
        .single() as any

    if (!profile?.company_id) return []

    const { data: payments } = await (supabase
        .from('payments') as any)
        .select('*, invoices(invoice_number, customer_snapshot)')
        .eq('company_id', profile.company_id)
        .order('created_at', { ascending: false })

    return payments || []
}

export async function recordPayment(prevState: any, formData: FormData) {
    const supabase = (await createClient()) as SupabaseClient<Database>
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { message: 'Not authenticated' }

    const { data: profile } = await supabase
        .from('profiles')
        .select('company_id')
        .eq('id', user.id)
        .single() as any

    if (!profile?.company_id) return { message: 'No company found' }

    const invoice_id = formData.get('invoice_id') as string
    const amount = parseFloat(formData.get('amount') as string)
    const payment_date = formData.get('payment_date') || new Date().toISOString()
    const mode = formData.get('mode') as string
    const notes = formData.get('notes') as string
    const reference_id = formData.get('reference_id') as string

    if (!invoice_id || !amount) {
        return { message: 'Invoice and Amount are required' }
    }

    // 3. Insert Payment
    const paymentResult = await (supabase.from('payments') as any)
        .insert({
            company_id: profile.company_id,
            invoice_id,
            amount,
            payment_date, // Store the actual date provided
            mode,
            notes,
            reference_id
            // receipt_number is auto-generated
        })
        .select()
        .single()

    const { error } = paymentResult
    const newPayment = paymentResult.data

    if (error) {
        return { message: error.message }
    }

    // 4. Update Invoice Status & Trigger Backup
    // Fetch Invoice Total and Existing Payments + Details for Backup
    const { data: invoice } = await (supabase.from('invoices') as any)
        .select('*, customer_snapshot')
        .eq('id', invoice_id)
        .single()

    const { data: allPayments } = await (supabase.from('payments') as any)
        .select('amount')
        .eq('invoice_id', invoice_id)

    if (invoice && allPayments) {

        const totalPaid = allPayments.reduce((sum: number, p: any) => sum + (p.amount || 0), 0)

        // Strict CA Logic: Paid if Total Paid >= Net Receivable (NOT Grand Total)
        const netReceivable = invoice.net_receivable || invoice.grand_total

        let newStatus = 'partially_paid'
        // Use a small epsilon for float comparison safety
        if (totalPaid >= (netReceivable - 1)) {
            newStatus = 'paid'
        }

        // Update Invoice
        await (supabase.from('invoices') as any)
            .update({ status: newStatus })
            .eq('id', invoice_id)

        // --- BACKUP SYSTEM (RECEIPT) ---
        try {
            // 1. We need the full payment record (with receipt number if DB trigger generated it)
            // `newPayment` from line 70 has what returned from insert.
            // If `receipt_number` is generated by DB default/trigger, we rely on the returned row.

            // 2. Fetch dependencies
            const { data: company } = await (supabase.from('companies') as any).select('*').eq('id', profile.company_id).single()

            // We already fetched `invoice` above (line 78).
            // `invoice` has `customer_snapshot` included.

            if (company && invoice && newPayment) {
                const { BackupService } = await import('@/lib/backup-service')
                // customer data is inside invoice.customer_snapshot or separate party fetch?
                // signature: backupReceipt(payment, invoice, company, customer)
                const customer = invoice.customer_snapshot || {}

                await BackupService.backupReceipt(newPayment, invoice, company, customer)
            }

            // --- AUDIT LOG ---
            const { logAuditEvent } = await import('./audit')
            await logAuditEvent(
                'payments',
                newPayment.id,
                'create',
                null,
                newPayment,
                `Payment of ₹${amount} recorded for Invoice ${invoice.invoice_number}`
            )

        } catch (e) { console.error('[Payment] Backup/Audit Failed:', e) }
        // --- BACKUP SYSTEM END ---
    }

    revalidatePath('/dashboard/payments')
    revalidatePath(`/dashboard/invoices/${invoice_id}`)
    revalidatePath('/dashboard')
    return { message: 'success' }
}

export async function getDashboardStats() {
    const supabase = (await createClient()) as SupabaseClient<Database>
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return getEmptyStats()

    const { data: profile } = await supabase
        .from('profiles')
        .select('company_id')
        .eq('id', user.id)
        .single() as any

    if (!profile?.company_id) return getEmptyStats()

    // 1. Fetch Invoices (Revenue, Outstanding, Aging, Locked TDS)
    // We need payments for each invoice to calculate true outstanding
    const { data: invoices } = await (supabase.from('invoices') as any)
        .select(`
            id, invoice_number, date, due_date, grand_total, status, customer_snapshot, 
            net_receivable, tds_amount, subtotal, tax_total
        `)
        .eq('company_id', profile.company_id)
        .neq('status', 'cancelled')
        .eq('is_deleted', false)
        .order('created_at', { ascending: false })

    // 2. Fetch Expenses (Total Expenses, Input GST)
    const { data: expenses } = await (supabase.from('expenses') as any)
        .select('id, date, amount, category, vendor_name, gst_amount')
        .eq('company_id', profile.company_id)
        .eq('is_deleted', false)
        .order('date', { ascending: false })

    // 3. Fetch Payments (Cash In Hand, Collections)
    const { data: payments } = await (supabase.from('payments') as any)
        .select('amount, payment_date, invoice_id')
        .eq('company_id', profile.company_id)

    // --- CALCULATIONS ---

    // A. Cash Flow & Profit
    const cashCollected = payments?.reduce((sum: number, p: any) => sum + (p.amount || 0), 0) || 0
    const totalExpenses = expenses?.reduce((sum: number, exp: any) => sum + (exp.amount || 0), 0) || 0

    // "Cash In Hand" (Operating Cash Flow)
    const cashInHand = cashCollected - totalExpenses

    // "Accounting Profit" (Invoiced Taxable - Expenses)
    const totalInvoicedTaxable = invoices?.reduce((sum: number, inv: any) => sum + (inv.subtotal || 0), 0) || 0
    const accountingProfit = totalInvoicedTaxable - (totalExpenses - (expenses?.reduce((sum: number, e: any) => sum + (e.gst_amount || 0), 0) || 0)) // Excl GST from expenses for true profit? 
    // Simplified: Revenue - Expenses. Let's stick to simple "Invoiced - Expense" for now as requested.
    // "Profit shown after expenses"

    // B. Receivables & Locked TDS
    let netReceivable = 0
    let lockedTDS = 0
    const today = new Date()

    // Aging Buckets
    const aging = {
        "0-15": 0,
        "16-30": 0,
        "31-45": 0,
        "45+": 0
    }

    invoices?.forEach((inv: any) => {
        // Locked TDS: Sum of all TDS where invoice is finalized (assuming deducted)
        if (inv.status !== 'draft' && inv.tds_amount > 0) {
            lockedTDS += inv.tds_amount
        }

        // Net Receivable: Calculate balance per invoice
        // Filter payments for this invoice
        const paidForInv = payments?.filter((p: any) => p.invoice_id === inv.id)
            .reduce((sum: number, p: any) => sum + (p.amount || 0), 0) || 0

        // Use updated field net_receivable or fallback to grand_total
        const receivableTotal = inv.net_receivable || inv.grand_total
        const balance = Math.max(0, receivableTotal - paidForInv)

        if (balance > 1 && inv.status !== 'cancelled' && inv.status !== 'draft') {
            netReceivable += balance

            // Aging (based on Invoice Date)
            const invDate = new Date(inv.date)
            const diffTime = Math.abs(today.getTime() - invDate.getTime())
            const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24))

            if (diffDays <= 15) aging["0-15"] += balance
            else if (diffDays <= 30) aging["16-30"] += balance
            else if (diffDays <= 45) aging["31-45"] += balance
            else aging["45+"] += balance
        }
    })

    // C. GST Liability
    // Output GST (from Invoices) - Input GST (from Expenses)
    const outputGST = invoices?.reduce((sum: number, inv: any) => sum + (inv.tax_total || 0), 0) || 0
    const inputGST = expenses?.reduce((sum: number, exp: any) => sum + (exp.gst_amount || 0), 0) || 0
    const gstLiability = Math.max(0, outputGST - inputGST)

    // D. Monthly Trends (Cash Flow based)
    const monthlyStats: any[] = []
    for (let i = 5; i >= 0; i--) {
        const d = new Date()
        d.setMonth(d.getMonth() - i)
        const monthKey = d.toLocaleString('default', { month: 'short' })
        const year = d.getFullYear()

        const monthPayments = payments?.filter((p: any) => {
            const pdate = new Date(p.payment_date)
            return pdate.getMonth() === d.getMonth() && pdate.getFullYear() === year
        })
        const monthExpenses = expenses?.filter((exp: any) => {
            const edate = new Date(exp.date)
            return edate.getMonth() === d.getMonth() && edate.getFullYear() === year
        })

        monthlyStats.push({
            name: monthKey,
            "Cash In": monthPayments?.reduce((s: number, p: any) => s + (p.amount || 0), 0) || 0,
            "Cash Out": monthExpenses?.reduce((s: number, e: any) => s + (e.amount || 0), 0) || 0
        })
    }

    return {
        cashInHand,
        netReceivable,
        lockedTDS,
        gstLiability,
        accountingProfit,
        invoiceCount: invoices?.length || 0,
        aging,
        monthlyStats,
        recentInvoices: invoices?.slice(0, 5) || [],
        recentExpenses: expenses?.slice(0, 5) || []
    }
}

function getEmptyStats() {
    return {
        cashInHand: 0,
        netReceivable: 0,
        lockedTDS: 0,
        gstLiability: 0,
        accountingProfit: 0,
        invoiceCount: 0,
        aging: { "0-15": 0, "16-30": 0, "31-45": 0, "45+": 0 },
        monthlyStats: [],
        recentInvoices: [],
        recentExpenses: []
    }
}
