import { numberToIndianRupees } from './number-utils'

export const renderReceiptHTML = (payment: any, invoice: any, company: any, customer: any) => {
    const logoUrl = `${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/logo.png`

    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <title>Receipt ${payment.receipt_number}</title>
        <style>
             @page { size: A4; margin: 0; }
             body { font-family: 'Inter', Helvetica, Arial, sans-serif; padding: 40px; color: #111; line-height: 1.5; }
             .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; border-bottom: 2px solid #f1f5f9; padding-bottom: 20px; }
             .logo-img { height: 60px; width: auto; object-fit: contain; }
             .receipt-details { text-align: right; }
             .receipt-title { font-size: 32px; color: #166534; font-weight: 700; margin-bottom: 5px; letter-spacing: -0.5px; }
             .meta { color: #64748b; font-size: 14px; font-weight: 500; }
             
             .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); opacity: 0.04; width: 400px; z-index: -1; pointer-events: none; }
             
             .content { margin-bottom: 40px; background: white; }
             .box { background: #f8fafc; padding: 30px; border-radius: 12px; border: 1px solid #e2e8f0; }
             .row { display: flex; justify-content: space-between; margin-bottom: 15px; font-size: 15px; border-bottom: 1px dashed #e2e8f0; padding-bottom: 10px; }
             .row:last-child { border-bottom: none; }
             .label { font-weight: 600; color: #64748b; }
             .value { font-weight: 600; color: #0f172a; }
             
             .amount-box { margin-top: 30px; text-align: center; background: #dcfce7; padding: 20px; border-radius: 8px; color: #14532d; border: 1px solid #bbf7d0; }
             .amount-label { font-size: 12px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 5px; font-weight: 700; }
             .amount-value { font-size: 32px; font-weight: 800; }
             
             .words-row { margin-top: 10px; text-align: center; }
             .words-text { font-family: 'Times New Roman', serif; font-style: italic; font-size: 16px; color: #15803d; }

             .footer { position: fixed; bottom: 40px; left: 40px; right: 40px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px solid #f1f5f9; padding-top: 20px; }
        </style>
    </head>
    <body>
        <img src="${logoUrl}" class="watermark" />
        
        <div class="header">
            <div class="logo">
                <img src="${logoUrl}" class="logo-img" alt="${company?.name}" />
            </div>
            <div class="receipt-details">
                <div class="receipt-title">PAYMENT RECEIPT</div>
                <div class="meta">#${payment.receipt_number || 'PENDING'}</div>
                <div class="meta">Date: ${new Date(payment.payment_date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</div>
            </div>
        </div>

        <div class="content">
            <div class="box">
                <div class="row">
                    <span class="label">Received From (Customer)</span>
                    <span class="value">${customer?.name}</span>
                </div>
                <div class="row">
                    <span class="label">Payment Mode</span>
                    <span class="value" style="text-transform: capitalize">${payment.mode}</span>
                </div>
                <div class="row">
                    <span class="label">Reference ID / Trans ID</span>
                    <span class="value">${payment.reference_id || 'N/A'}</span>
                </div>
                <div class="row">
                    <span class="label">Against Invoice</span>
                    <span class="value">${invoice?.invoice_number}</span>
                </div>
                
                <div class="amount-box">
                    <div class="amount-label">Amount Received</div>
                    <div class="amount-value">₹${payment.amount.toLocaleString('en-IN')}</div>
                    <div class="words-row">
                        <div class="words-text">${numberToIndianRupees(payment.amount)}</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer">
            <p>This is a computer generated receipt and does not require a physical signature.</p>
            <p>Generated by CitruX Billing System • ${company?.website || 'www.citrux.com'}</p>
        </div>
    </body>
    </html>
    `
}
